Ebank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('transactions.urls')),
    path('', include('django.contrib.auth.urls')),
    path('account', include('authz.urls')),
]

authz/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'authz'
urlpatterns = [
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("signup", views.signup, name="signup"),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
   
]

transactions/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'transactions'
urlpatterns = [
    path("", views.index, name="index"),
    path('dashboard', views.dashboard.as_view(), name="dashboard"),
]

authz/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

class CustomUserManager(BaseUserManager):
    def _create_user(self,email,password, first_name, last_name, phone_num, date_of_birth,sex, country,state_of_origin, address,**extra_fields):
        if not email:
            raise valueerror("Email must be provided")
        if not password:
            raise valueerror("Password must be provided")

        user = self.model(
            email  = self.normalize_email(email),
            first_name = first_name,
            last_name = last_name,
            phone_num = phone_num,
            date_of_birth = date_of_birth,
            sex = sex,
            country = country,
            state_of_origin = state_of_origin,
            address= address,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, first_name, last_name,phone_num, date_of_birth,sex,country,state_of_origin,address, **extra_fields):
        extra_fields.setdefault('is_staff',False)
        extra_fields.setdefault('is_active',True)
        extra_fields.setdefault('is_superuser',False)
        extra_fields.setdefault('is_email_verified',False)
        extra_fields.setdefault('is_document_submitted',False)
        extra_fields.setdefault('is_document_verified',False)
        return self._create_user(email, password,first_name, last_name, phone_num, date_of_birth,sex, country, state_of_origin, address)

    def create_superuser(self, email, password,**extra_fields):
        extra_fields.setdefault('is_staff',True)
        extra_fields.setdefault('is_active',True)
        extra_fields.setdefault('is_superuser',True)
        extra_fields.setdefault('is_email_verified',True)
        extra_fields.setdefault('is_document_submitted',True)
        extra_fields.setdefault('is_document_verified',True)
        return self._create_user(email, password,first_name=None, last_name=None, 
        phone_num=None, date_of_birth=None, country=None, state_of_origin= None, address= None,sex=None, **extra_fields)


class User(AbstractBaseUser,PermissionsMixin):
    email= models.EmailField(unique=True, max_length=254)
    first_name = models.CharField(max_length=240, null=True)
    last_name = models.CharField(max_length=240, null=True)
    phone_num = models.CharField(max_length=50, null=True)
    date_of_birth = models.CharField(max_length=50, null=True)
    sex = models.CharField(max_length=5, null=True)
    country = models.CharField(max_length=50, null=True)
    state_of_origin = models.CharField(max_length=50, null=True)
    address = models.TextField(null=True)
    is_staff = models.BooleanField(default=False)
    is_active =  models.BooleanField(default=True)
    is_superuser =  models.BooleanField(default=False)
    is_document_submitted = models.BooleanField(default=False)
    is_document_verified = models.BooleanField(default=False)
    is_email_verified = models.BooleanField(default=False)
    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELD = ['email']

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

transactions/models.py
from django.db import models

# Create your models here.

authz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import User
from django.contrib.auth.models import auth
# Create your views here.
def login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = auth.authenticate(email=email, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('transactions:dashboard')
        else:
            messages.info(request, 'Invalid Email or password')
            return redirect('authz:login')

    return render(request, "authz/login.html")

def logout(request):
    auth.logout(request)
    return redirect('/')

def signup(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        date_of_birth = request.POST['date_of_birth']
        sex = request.POST['sex']
        country = request.POST['country']
        state_of_origin = request.POST['state_of_origin']
        address = request.POST['address']
        phone_num = request.POST['phone_num']

        if password == confirm_password:
            if User.objects.filter(email=email).exists():
                messages.info(request, "Email already exist")
                return redirect('authz:signup')
            else:
                user = User.objects.create_user(first_name=first_name, last_name=last_name, email=email, password=password,
                    date_of_birth= date_of_birth, sex = sex,country = country,phone_num=phone_num, state_of_origin = state_of_origin,address=address)
                user.save()
                messages.info(request, "Account created")
                return redirect('authz:login')
        else:
            messages.info(request, "Password didnt match")
            return redirect('authz:signup')
    return render(request, "authz/signup.html")

transactions/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

# Create your views here.

def index(request):
    if request.user.is_authenticated:
        return redirect('transactions:dashboard')
    context = {}
    return render(request, "transactions/index.html", context)

class dashboard(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        context={}
        return render(request, "transactions/dashboard.html",context)

authz/templates/authz/login.html
<h1>login page</h1>
{% for message in messages %}
<p>{{ message }}</p>
{% endfor %}
<form action="{% url 'authz:login' %}" method="POST">
{% csrf_token %}
<label for="email">Email:</label> <br>
<input type="email" name="email"><br>
<label for="password">Password:</label><br>
<input type="password" name="password"><br>
<button type="submit">Log in</button><br>

<a href="{% url 'authz:password_reset'%}" class="forgot-passwor-link">Forgot Password?</a>

</form>

<p>Don't have an account yet? <a href="{% url 'authz:signup' %}">Sign up</a> here</p>
<p><a href="{% url 'transactions:index' %}">Home</a></p>

authz/templates/authz/signup.html
<h1>Sign up</h1>
{% for message in messages %}
<p>{{ message }}</p>
{% endfor %}
<form action="{% url 'authz:signup' %}" method="POST">
    {% csrf_token %}
<!-- <label for="username">Username: </label><br>
<input type="text" required name="username"><br> -->
<label for="email">Email address:</label><br>
<input type="email" name="email"  required> <br>
<label for="first_name">First name:</label><br>
<input type="text" required name="first_name"><br>
<label for="last_name">Last_name:</label><br>
<input type="text" name="last_name" required><br>
<label for="phone_num">Phone Number:</label><br>
<input type="tel" name="phone_num"><br>
<label for="last_name">Date of Birth:</label><br>
<input type="date" name="date_of_birth" required><br>
<label for="sex">Sex:</label><br>
<select name="sex" id=""> --Select one--

    <option value="M">Male</option>
    <option value="F">Female</option>
</select><br>
<label for="country">Country:</label><br>
<input type="text" name="country" required><br>
<label for="state_of_origin">State of Origin:</label><br>
<input type="text" name="state_of_origin"><br>
<label for="address">Address:</label><br>
<textarea name="address" id="" cols="30" rows="10"></textarea><br>
<label for="password1">Password:</label><br>
<input type="password" name="password" required><br>
<label for="confirm_password">Confirm Password</label><br>
<input type="password" name="confirm_password"><br>

<button type="submit">Submit</button>
</form>


<p>Don't have an account yet? <a href="{% url 'authz:login' %}">Log in</a> here</p>
<p><a href="{% url 'transactions:index' %}">Home</a></p>

transactions/templates/transactions/dashboard.html
welcome {{user.first_name}}

<button><a href="{% url 'authz:logout' %}">Logout</a></button>

transactions/templates/transactions/index.html
<h1>Welcome to Mbawike Mobile money </h1>

<p>Please proceed with account creation/login</p>

<ul>
    <li>
        <button><a href="{% url 'authz:login' %}">Login</a></button>
    </li>
    <li>
       <button> <a href="{% url 'authz:signup' %}">Sign up</a></button>
    </li>
</ul>